# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8040528b2a34e7512af36ec9828d270d5d322e2cb04ec90112d6cf56585f0531ba9e65de409e6ab8c65f880da8078564279eea38760db1041acf361c86e38726

test:
  secret_key_base: 306e155c747ce9502695e41ebbaf9566898f15ea2d063a6ed91b63a4dbfd09914d02921b068937440595fdd87fdb32007f4d83f362d3394ad4ce28a8f28e3a18

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
